# statestore.yaml for Azure Blob storage component: https://learn.microsoft.com/en-us/azure/container-apps/microservices-dapr?tabs=bash#configure-the-state-store-component
componentType: state.azure.blobstorage
version: v1
metadata:
- name: accountName
  value: "sadaprstatenov2022"
- name: accountKey
  secretRef: account-key
- name: containerName
  value: counterstate
secrets:
- name: account-key
  value: <INSERT_ACCOUNT_KEY_HERE>
scopes:
- counter-api